version: '3'
services:
  web:
    image: game-ui
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/app/.env

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/quiddlerqueen.com:/etc/nginx/certs
      - ./sites-enabled:/etc/nginx/sites-enabled
    links:
      - web