version: '3'
services:
  web:
    image: game-ui
    ports:
      - 3000:3000
    volumes:
      - ./.env:/app/.env

  nginx:
    image: erangaeb/senznginx:0.4
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    links:
      - web