version: '3'
services:
  game-app:
    image: game-app
    volumes:
      - ./:/app

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/site.conf:/etc/nginx/sites-enabled/site.conf
      - ./certs:/etc/nginx/certs
    links:
      - game-app