import { v4 as uuidv4 } from 'uuid';
export const Deck: Deck = [
    ...Array(10).fill({id: uuidv4(), label: 'A', score: 2 }),
    ...Array(2).fill({id: uuidv4(), label: 'B', score: 8 }),
    ...Array(2).fill({id: uuidv4(), label: 'C', score: 8 }),
    ...Array(4).fill({id: uuidv4(), label: 'D', score: 4 }),
    ...Array(12).fill({id: uuidv4(), label: 'E', score: 2 }),
    ...Array(2).fill({id: uuidv4(), label: 'F', score: 6 }),
    ...Array(4).fill({id: uuidv4(), label: 'G', score: 6 }),
    ...Array(2).fill({id: uuidv4(), label: 'H', score: 7 }),
    ...Array(8).fill({id: uuidv4(), label: 'I', score: 2 }),
    ...Array(2).fill({id: uuidv4(), label: 'J', score: 13 }),
    ...Array(2).fill({id: uuidv4(), label: 'K', score: 8 }),
    ...Array(4).fill({id: uuidv4(), label: 'L', score: 3 }),
    ...Array(2).fill({id: uuidv4(), label: 'M', score: 5 }),
    ...Array(6).fill({id: uuidv4(), label: 'N', score: 5 }),
    ...Array(8).fill({id: uuidv4(), label: 'O', score: 2 }),
    ...Array(2).fill({id: uuidv4(), label: 'P', score: 6 }),
    ...Array(2).fill({id: uuidv4(), label: 'Q', score: 15 }),
    ...Array(6).fill({id: uuidv4(), label: 'R', score: 5 }),
    ...Array(4).fill({id: uuidv4(), label: 'S', score: 3 }),
    ...Array(6).fill({id: uuidv4(), label: 'T', score: 3 }),
    ...Array(6).fill({id: uuidv4(), label: 'U', score: 4 }),
    ...Array(2).fill({id: uuidv4(), label: 'V', score: 11 }),
    ...Array(2).fill({id: uuidv4(), label: 'W', score: 10 }),
    ...Array(2).fill({id: uuidv4(), label: 'X', score: 12 }),
    ...Array(4).fill({id: uuidv4(), label: 'Y', score: 4 }),
    ...Array(2).fill({id: uuidv4(), label: 'Z', score: 14 }),
    ...Array(2).fill({id: uuidv4(), label: 'ER', score: 7 }),
    ...Array(2).fill({id: uuidv4(), label: 'CL', score: 10 }),
    ...Array(2).fill({id: uuidv4(), label: 'IN', score: 7 }),
    ...Array(2).fill({id: uuidv4(), label: 'TH', score: 9 }),
    ...Array(2).fill({id: uuidv4(), label: 'QU', score: 9 }),
]

export function getShuffledDeck(): Deck {
    return [...Deck.sort(() => Math.random() - 0.5)];
}

export const DescCartCount = {
    a: 10,
    b: 2,
    c: 2,
    d: 4,
    e: 12,
    f: 2,
    g: 4,
    h: 2,
    i: 8,
    j: 2,
    k: 2,
    l: 4,
    m: 2,
    n: 6,
    o: 8,
    p: 2,
    q: 2,
    r: 6,
    s: 4,
    t: 6,
    u: 6,
    v: 2,
    w: 2,
    x: 2,
    y: 4,
    z: 2,
    er: 2,
    cl: 2,
    in: 2,
    th: 2,
    qu: 2
}